# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37669e7cdf53f815e464c23948675b4595a7f025510838571e9870ae8fc8270e53cc950081b24341bdef36b59af569da70577ef2bb0fada552016b2fd084ee4b

test:
  secret_key_base: efc017e064ef7dad1b8e51c424a65e6d175872e9de10364f64091a53848e4cf09741a8bcdf50f0947fdef58b5a3d3b671056683ba844f50e609437fffd2b65f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
